[[redirects]]
  from = "/*"
  to = "/"
  status = 200

  [[redirects]]
  from = "/assets/*.otf"
  to = "/assets/:splat"
  status = 200
  force = true
  headers = { Content-Type = "font/otf" }

  [[redirects]]
  from = "/assets/*.ttf"
  to = "/assets/:splat"
  status = 200
  force = true
  headers = { Content-Type = "font/ttf" }